language: java

sudo: required

env:
  - secure: mk2ure2QP6TCKMFLgSnTgr07XjQupY3HIzTZk/kY4EeuqA64nHWbCO8i0G3NEbeNSOf1D+mBl60ylyw35V4wIKwqpgBe+MvhtLk5wayvdjJhMTTBzV5EXV0kKVJtTphRXRwVxz8KJOipyEQl/v/eqt1Lfx4wj3N/3EKneiSscfv+SNhpv+jtEgTq4MXKvEONuWm4Dkn+bTcNUbqQzK72+4+sEF/JShIVU8Gw8tfgSXirBf9kqjhzIer9WoYQwVAsBy1udVOaYSPYLNfejDt57HXJjnLb5cUttZ7tkKBVnSPPeW0xyg9SqIIv2y2aVmPo5PqZ/KN9L+B2Swz2O+RLRSOZ8ewJZ3WMX8K4bpBrs5Q97cTXYX/FnKpG2L4xzlJtZMvgUFaJeFMCgJhVHVHVljNuedGZeum7rTCfSB8YZemuaNgecf0CM9rCUxO3wQ1MbGM24dX2Hdwjo2Cc+l3BeujMFtEwPrlasKRJk1sHIufKhEYkh6JWHEX5jA3E3pJZDF9U19RwV4eS9DXymlHEcUqaBBuZ6F5ojb/xtuTLyMlI5XK4G/K//BsQEpkRm6aut0Qt684t7X7vmbh3EKeRXLXbury9XCXRMqBgfRfQwZiKZM61U7/nXJWIrnQ+25aiyqjL1vzNFhPDMbVQ/Uu0q2ApQ3bfxm+aeyXnU3hRHRs=

services:
  - docker

before_install:
  - cd docker && bash build.sh && bash tag.sh && cd ..

install:
  - curl -fsSL get.nextflow.io | bash 
  - export PATH="`pwd`:${PATH}"

script:
  - cd test && bash setup_test.sh && cd ..
  - nextflow distiller.nf -params-file ./test/test_project.yml

deploy:
  provider: script
  script: cd docker && bash deploy.sh
  on:
    repo: mirnylab/distiller-nf
    branch: master
    tags: true
