language: java

sudo: required

env:
  - secure: Ks28jjYkehV2LIcvKE8dgoREnqca3qu8GQF2Bc3hPgDtmEjPTRzysDldok21+OMI0nZRVAep6VNBmnJk5NnJuwHTGyVAruZIx2tf0GxLtt11JIdYUnPobdhBKfzMLCnovdIINvbEriu9RtR1a2+wJCDRLfvKXcv2HsgENJOIrFHJyyOs2zCwJ6Cbc3MlUUXtNoL47rNHNqMR387zkj9AqTewkugTBqFCTOJ/f7jorrKWWHUp5AfH94JBfWp9G0IlRN5+oxRMSeQzcE2Xpc1saoPvtKzkQOw21MvNzxt3WQx21GDnmJIjF7wOkIabQj31+JtmEoa9hoynfWqWhmwbXaS2FYTcUwQykhyIoZVroVXXHxsdsKi6xKDx/iPPsKXz5da4XMtQSxuhLfuhDanjWNStfZEyvK3bU2+4UvzzAjQCR2skrZqyKTtLCbBS2ZH14YXuMz/QgBlXT34GlP4ehQnmXsP4cejFZNckVQDBraK9PNVVSxcXrMW1uTnz9kcDq6wWU7hI97mGKS1oDqZSRBW81PObEIiTSkm2f8hzTQpjbuA6djtjU/CoUGDeegTXyGwnKrvPEMVoq47u0dQiw1PTMrr3Ula/vVvtnQSMobov6En0owFh/6VT95ty7psOUSyUFcTRy6bd6j2E+HrzCJTr3K48JiqfR7qx8ep5TkI=

services:
  - docker

before_install:
  - cd docker && bash build.sh && bash tag.sh && cd ..

install:
  - curl -fsSL get.nextflow.io | bash 
  - export PATH="`pwd`:${PATH}"

script:
  - cd test && bash setup_test.sh && cd ..
  - nextflow distiller.nf -params-file ./test/test_project.yml

deploy:
  provider: script
  script: cd docker && bash deploy.sh
  on:
    repo: mirnylab/distiller-nf
    branch: master
    tags: true
