os:
    - linux
    - osx

language: java

sudo: required

services:
    - docker

before_install:
    - docker pull mirnylab/distiller_env:latest

install:
    - curl -fsSL get.nextflow.io | bash 
    - export PATH="`pwd`:${PATH}"

script:
    - bash setup_test.sh
    - nextflow distiller.nf -params-file project.yml
