os:
    - linux
    - osx

#sudo: required
sudo: false

language: groovy

services:
    - docker

before_install:
    - docker pull mirnylab/distiller_env:latest

script:
    - curl -fsSL get.nextflow.io | bash 
    - bash setup_test.sh
    - ./nextflow distiller.nf -params-file project.yml
