language: java

sudo: required

env:
  - secure: cmXh4ippopUCARwFEptV8rIPgo5CUaAHVirtXzr7k78ntL/MTmMMJ9D4o2MDh/gK5TqWGlmxt+MF4INGY8NPqgCRLVeGkDc1sIE77zso6LGCZ0XLUZx05OQ0z/e/qWXLdvsPKoA4oKg19g53KEkfp2iE/ltJilXTJQY5TD7yM4yxGOgGkTdtt3ijLp6CjFHZkIqe5jrZQmwU8jrCojKBiK4/MjiAJo7OPhtP7+O4ljM7flKMZje2gVvb7c9/pHvkllLQZ7qiOdAeGuO9onQwKhGVq/jVXo0UrFgifpKcnQwl0Ok8dpijcQ55DRl2iOoM9svbjdpJw9DfyUJuRWcR5U5oMDP4i9H3BZcl9Z6WmaRDGKh1DnI6C4ahnRpn2TmclWBGolX+fRMwTPBKUrlUqTlXGbcMTRU3zLzzKFrBn0xVDpBWQHW0IabmLL4kK6yqAFFZ9RVlwYo+UHSziM8zAc/qoX7OkSxJ9ZRukJagGwq9DPega7siY5eZKdRqI7frv3rUtmgpFLPRYbD6+WXcfmLnE1bg81fmkJXTMR95odJhFUQOqfGwswC8QhhOxJr5YgFcg34XYjCidzlCsfRYBPV8bcSvDR23EQcQbR4b90Fe0pqhbY50tzZS1d72LA6hmY5RkIdrKAB4KFld70rZA2+S6MGT4ruoEZ76oRsN9Oc=

services:
  - docker

before_install:
  - cd docker && bash build.sh && bash tag.sh && cd ..

install:
  - curl -fsSL get.nextflow.io | bash 
  - export PATH="`pwd`:${PATH}"

script:
  - cd test && bash setup_test.sh && cd ..
  - nextflow distiller.nf -params-file ./test/test_project.yml

deploy:
  provider: script
  script: cd docker && bash deploy.sh
  on:
    repo: mirnylab/distiller-nf
    branch: master
    tags: true
