#########################################
# THIS IS A TYPICAL project.yml TEMPLATE
# most of the settings present here
# are GO for mapping production data
# but nonetheless user must consider
# carefully every presented option
#########################################


# choose if you want to do FastQC:
do_fastqc: False
    
#######################################
# provide paths to your raw input data (fastq-s):
#######################################
# Fastqs can be provided as:
# -- a pairs of relative/absolute paths
# -- sra:<SRA_NUMBER>, optionally followed by the indices of the first and
# the last entry in the SRA in the form of "?start=<first>&end=<last>
input:
    # truncate input fastqs to a small number of reads (e.g. 10000) for
    # semi-dry test runs.
    truncate_fastq_reads: 0
    raw_reads_paths:
        # substitute the location of your fastq files:
        # an example of a 1-lane library:
        your_library_name_1:
            lane1:
                - /path/to/your/fastq/from/library1/library1_side1.fastq.gz
                - /path/to/your/fastq/from/library1/library1_side2.fastq.gz
        # an example of a 2-lane library:
        # mapped reads from both lanes will be pulled togheter
        # and deduplicated as one.
        your_library_name_2:
            lane1:
                - /path/to/your/fastq/from/library1/library2_lane1_side1.fastq.gz
                - /path/to/your/fastq/from/library1/library2_lane1_side2.fastq.gz
            lane2:
                - /path/to/your/fastq/from/library1/library2_lane2_side1.fastq.gz
                - /path/to/your/fastq/from/library1/library2_lane2_side2.fastq.gz
        # an example of a 3-lane library:
        # mapped reads from both lanes will be pulled togheter
        # and deduplicated as one.
        your_library_name_3:
            lane1:
                - /path/to/your/fastq/from/library1/library3_lane1_side1.fastq.gz
                - /path/to/your/fastq/from/library1/library3_lane1_side2.fastq.gz
            lane2:
                - /path/to/your/fastq/from/library1/library3_lane2_side1.fastq.gz
                - /path/to/your/fastq/from/library1/library3_lane2_side2.fastq.gz
            lane3:
                - /path/to/your/fastq/from/library1/library3_lane3_side1.fastq.gz
                - /path/to/your/fastq/from/library1/library3_lane3_side2.fastq.gz
        your_library_online:
            lane1:
                # Files can be provided as http/ftp/s3 links
                - https://github.com/mirnylab/distiller-test-data/raw/master/fastq/MATalpha_R1/lane2/SRR2601843_1.fastq.gz
                - https://github.com/mirnylab/distiller-test-data/raw/master/fastq/MATalpha_R1/lane2/SRR2601843_2.fastq.gz
            lane2:
                # Alternatively, reads can be downloaded from SRA
                - sra:SRR2601842
            lane3:
                # or like that:
                - sra:SRR2601843?start=0&end=10000


    # independent libraries can be combined together
    # on the level of binned-data (.cool files)
    # describe your groupings of choice here:
    library_groups:
        libraries_1_and_2:
            - your_library_name_1
            - your_library_name_2
        all_libraries:
            - your_library_name_1
            - your_library_name_2
            - your_library_name_3
            - your_library_online


    # provide a refence genome to map your raw reads to.
    # BWA-indexed genome and a file with chromosome names and sizes are required.
    genome:
        assembly: 'hg19'
        bwa_index_wildcard: '/path/to/your/reference/genome/hg19.fa.*'
        chrom_sizes_path:   '/path/to/your/reference/genome/hg19.reduced.chrom.sizes'


# choose mapping and pairsamtools
# processing parameters.
map:
    # uncomment to split each run into chunks which are mapped separately.
    # Useful for mapping on clusters with many relatively weak nodes.
    # The optimal chunk size is defined by the balance between mapping and merging.
    # Smaller chunks (~30M) are better for clusters with many weak nodes,
    # however, having >~10 chunks per run can lead to very slow merging.
    
    #chunksize: 100000000
    
    # drop following entries from file with pairs
    # to speed up processing, or keep them for debugging:
    
    drop_sam: True
    drop_readid: True
    drop_seq: True
    keep_unparsed_bams: True

    # more BWA mapping options.
    
    # mapping_options: ''


# pairs deduplication parameter:
filter:
    pcr_dups_max_mismatch_bp: 1


# binning parameters for cooler:
bin:
    # pick your resolutions of choice:
    resolutions:
        - 1000000
        - 500000
        - 200000
        - 100000
        - 40000
        - 20000
        - 10000
        - 5000
        - 1000
    # additional balancing parameters:
    # balance_options: ''
    filters:
        no_filter: ''
        mapq_30: '(int(mapq1)>=30) and (int(mapq2)>=30)'


########################################
# folder structure for storing results
########################################
intermediates:
    base_dir: 'results/intermediates/'
    dirs:
        downloaded_fastqs: 'downloaded_fastqs/'
        fastq_chunks: 'fastq_chunks'
        mapped_parsed_sorted_chunks: 'mapped_parsed_sorted_chunks'
        pairsam_library: 'pairs_library'

output:
    base_dir: 'results/output/'
    dirs:
        fastqc: 'fastqc/'
        stats_chunk: 'stats/chunk/'
        stats_run: 'stats/run/'
        stats_library: 'stats/library/'
        stats_library_group: 'stats/library_group/'
        coolers_library: 'coolers/library/'
        coolers_library_group: 'coolers/library_group/'
        zoom_coolers_library: 'coolers/library_zoom/'
        zoom_coolers_library_group: 'coolers/library_group_zoom/'
        bams_library: 'bams/library/'

